import { Product } from '../types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'flw-001',
    name: 'Blush Ivory Royal Box',
    slug: 'blush-ivory-royal-box',
    category: 'Flower Boxes',
    subCategory: 'Hat Box Arrangements',
    occasion: 'Anniversary',
    recipient: 'For Her',
    flowerType: 'Roses',
    price: 23602,
    originalPrice: 33750,
    stock: 36,
    images: ['/images/products/blush-ivory-royal-box.webp'],
    rating: 4.9,
    reviewsCount: 181,
    tag: 'Florist Choice',
    description: "A lavish curation of handpicked roses, masterfully arranged in Dhanvikk's signature French velvet keepsake box. Accented with lush spiral eucalyptus and tied with an ivory satin ribbon.",
    isBestSeller: true,
    isFeatured: true,
    inStock: true,
  },
  {
    id: 'flw-002',
    name: 'Eternal Harmony Roses',
    slug: 'eternal-harmony-roses',
    category: 'Forever Roses',
    subCategory: 'Preserved Bell Domes',
    occasion: 'Anniversary',
    recipient: 'For Her',
    flowerType: 'Roses',
    price: 10102,
    originalPrice: 12375,
    stock: 27,
    images: ['/images/products/eternal-harmony-roses.webp'],
    rating: 5.0,
    reviewsCount: 140,
    tag: 'Signature Atelier',
    description: 'A breathtaking showcase of naturally preserved Ecuadorian roses, meticulously stabilized to retain velvety softness, vibrant pigment, and structural perfection for up to 3 years without watering.',
    isBestSeller: true,
    isFeatured: false,
    inStock: true,
  },
  {
    id: 'flw-003',
    name: 'Ocean Whisper Luxury Box',
    slug: 'ocean-whisper-luxury-box',
    category: 'Flower Boxes',
    subCategory: 'Hat Box Arrangements',
    occasion: 'Congratulations',
    recipient: 'Everyone',
    flowerType: 'Mixed',
    price: 9652,
    originalPrice: 12375,
    stock: 28,
    images: ['/images/products/ocean-whisper-luxury-box.webp'],
    rating: 5.0,
    reviewsCount: 74,
    tag: 'Luxury Edit',
    description: "A lavish curation of handpicked garden blooms, masterfully arranged in Dhanvikk's signature French velvet keepsake box with lush spiral eucalyptus.",
    isBestSeller: false,
    isFeatured: true,
    inStock: true,
  },
  {
    id: 'flw-004',
    name: 'Azure Majesty Hat Box',
    slug: 'azure-majesty-hat-box',
    category: 'Flower Boxes',
    subCategory: 'Hat Box Arrangements',
    occasion: 'Anniversary',
    recipient: 'For Her',
    flowerType: 'Mixed',
    price: 11228,
    originalPrice: 11250,
    stock: 20,
    images: ['/images/products/azure-majesty-hat-box.webp'],
    rating: 5.0,
    reviewsCount: 113,
    tag: 'Best Seller',
    description: "A lavish curation of handpicked garden blooms, masterfully arranged in Dhanvikk's signature French velvet keepsake box.",
    isBestSeller: false,
    isFeatured: true,
    inStock: true,
  },
  {
    id: 'flw-005',
    name: 'Crimson Royal Grandeur',
    slug: 'crimson-royal-grandeur',
    category: 'Flowers',
    subCategory: 'Hand Bouquets',
    occasion: 'Love & Romance',
    recipient: 'For Her',
    flowerType: 'Roses',
    price: 11228,
    originalPrice: 13500,
    stock: 15,
    images: ['/images/products/crimson-royal-grandeur.webp'],
    rating: 4.9,
    reviewsCount: 146,
    tag: 'Artisan Hand-tied',
    description: 'Hand-tied by master Parisian florists, the Crimson Royal Grandeur harmonizes premium long-stemmed roses with fresh seasonal textural greens.',
    isBestSeller: true,
    isFeatured: false,
    inStock: true,
  },
  {
    id: 'flw-006',
    name: 'Sunshine Lily Bouquet',
    slug: 'sunshine-lily-bouquet',
    category: 'Flowers',
    subCategory: 'Hand Bouquets',
    occasion: 'Birthday',
    recipient: 'BFFs',
    flowerType: 'Lilies',
    price: 6728,
    originalPrice: 7875,
    stock: 41,
    images: ['/images/products/sunshine-lily-bouquet.webp'],
    rating: 4.8,
    reviewsCount: 172,
    tag: 'Artisan Hand-tied',
    description: 'Hand-tied by master Parisian florists, the Sunshine Lily Bouquet harmonizes premium long-stemmed lilies with fresh seasonal textural greens.',
    isBestSeller: false,
    isFeatured: false,
    inStock: true,
  },
  {
    id: 'flw-007',
    name: 'Golden Lily Bouquet',
    slug: 'golden-lily-bouquet',
    category: 'Flowers',
    subCategory: 'Hand Bouquets',
    occasion: 'Anniversary',
    recipient: 'For Her',
    flowerType: 'Lilies',
    price: 6728,
    originalPrice: 7875,
    stock: 38,
    images: ['/images/products/golden-lily-bouquet.webp'],
    rating: 4.7,
    reviewsCount: 45,
    tag: 'Limited Edition',
    description: 'Hand-tied by master Parisian florists, the Golden Lily Bouquet harmonizes premium long-stemmed lilies with fresh seasonal textural greens.',
    isBestSeller: false,
    isFeatured: true,
    inStock: true,
  },
  {
    id: 'flw-008',
    name: 'Sunset Orange Lily Vase',
    slug: 'sunset-orange-lily-vase',
    category: 'Flowers',
    subCategory: 'Vase Arrangements',
    occasion: 'Anniversary',
    recipient: 'For Her',
    flowerType: 'Lilies',
    price: 4478,
    originalPrice: 5625,
    stock: 42,
    images: ['/images/products/sunset-orange-lily-vase.webp'],
    rating: 4.8,
    reviewsCount: 141,
    tag: 'Best Seller',
    description: 'Architecturally balanced lilies nestled in an artisan fluted lead-free crystal glass vase. Styled with fragrant silvery spiral eucalyptus.',
    isBestSeller: true,
    isFeatured: false,
    inStock: true,
  },
  {
    id: 'flw-009',
    name: 'Pink Lily Grace Vase',
    slug: 'pink-lily-grace-vase',
    category: 'Flowers',
    subCategory: 'Vase Arrangements',
    occasion: 'Congratulations',
    recipient: 'For Her',
    flowerType: 'Lilies',
    price: 6728,
    originalPrice: 7875,
    stock: 29,
    images: ['/images/products/pink-lily-grace-vase.webp'],
    rating: 5.0,
    reviewsCount: 123,
    tag: 'Luxury Edit',
    description: 'Architecturally balanced lilies nestled in an artisan fluted lead-free crystal glass vase. Styled with fragrant silvery spiral eucalyptus.',
    isBestSeller: false,
    isFeatured: false,
    inStock: true,
  },
  {
    id: 'flw-010',
    name: 'Celestial Paradise Vase',
    slug: 'celestial-paradise-vase',
    category: 'Flowers',
    subCategory: 'Vase Arrangements',
    occasion: 'Birthday',
    recipient: 'Everyone',
    flowerType: 'Mixed',
    price: 11228,
    originalPrice: 13500,
    stock: 34,
    images: ['/images/products/celestial-paradise-vase.webp'],
    rating: 4.9,
    reviewsCount: 78,
    tag: 'Artisan Hand-tied',
    description: 'Architecturally balanced garden blooms nestled in an artisan fluted lead-free crystal glass vase.',
    isBestSeller: false,
    isFeatured: true,
    inStock: true,
  },
  {
    id: 'flw-011',
    name: 'Crimson Elegance in Pinnacle',
    slug: 'crimson-elegance-in-pinnacle',
    category: 'Flowers',
    subCategory: 'Hand Bouquets',
    occasion: 'Love & Romance',
    recipient: 'For Her',
    flowerType: 'Roses',
    price: 27000,
    originalPrice: 35100,
    stock: 33,
    images: ['/images/products/crimson-elegance-in-pinnacle.webp'],
    rating: 4.8,
    reviewsCount: 172,
    tag: 'Artisan Hand-tied',
    description: 'Hand-tied by master Parisian florists, the Crimson Elegance in Pinnacle harmonizes premium long-stemmed roses with fresh seasonal textural greens.',
    isBestSeller: true,
    isFeatured: false,
    inStock: true,
  },
  {
    id: 'flw-012',
    name: 'Eternal Ivory Majesty',
    slug: 'eternal-ivory-majesty',
    category: 'Forever Roses',
    subCategory: 'Preserved Bell Domes',
    occasion: 'Anniversary',
    recipient: 'For Her',
    flowerType: 'Mixed',
    price: 11247,
    originalPrice: 14622,
    stock: 15,
    images: ['/images/products/eternal-ivory-majesty.webp'],
    rating: 4.7,
    reviewsCount: 94,
    tag: 'Artisan Hand-tied',
    description: 'A breathtaking showcase of naturally preserved Ecuadorian garden blooms, meticulously stabilized to retain velvety softness and vibrant pigment.',
    isBestSeller: false,
    isFeatured: true,
    inStock: true,
  },
  {
    id: 'flw-013',
    name: 'Royal Harvest Grandeur',
    slug: 'royal-harvest-grandeur',
    category: 'Flowers',
    subCategory: 'Hand Bouquets',
    occasion: 'Congratulations',
    recipient: 'Everyone',
    flowerType: 'Mixed',
    price: 3375,
    originalPrice: 4387,
    stock: 35,
    images: ['/images/products/royal-harvest-grandeur.webp'],
    rating: 4.8,
    reviewsCount: 49,
    tag: 'Trending Now',
    description: 'Hand-tied by master Parisian florists, the Royal Harvest Grandeur harmonizes premium long-stemmed garden blooms with fresh seasonal textural greens.',
    isBestSeller: false,
    isFeatured: true,
    inStock: true,
  },
  {
    id: 'flw-014',
    name: 'Champagne Garden Luxe',
    slug: 'champagne-garden-luxe',
    category: 'Flowers',
    subCategory: 'Hand Bouquets',
    occasion: 'Birthday',
    recipient: 'Everyone',
    flowerType: 'Mixed',
    price: 15728,
    originalPrice: 20452,
    stock: 21,
    images: ['/images/products/champagne-garden-luxe.webp'],
    rating: 5.0,
    reviewsCount: 74,
    tag: 'Signature Atelier',
    description: 'Hand-tied by master Parisian florists, the Champagne Garden Luxe harmonizes premium long-stemmed garden blooms.',
    isBestSeller: true,
    isFeatured: false,
    inStock: true,
  },
  {
    id: 'flw-015',
    name: 'Baby Boy Harmony Celebration Box',
    slug: 'baby-boy-harmony-celebration-box',
    category: 'Flower Boxes',
    subCategory: 'Hat Box Arrangements',
    occasion: 'Congratulations',
    recipient: 'Everyone',
    flowerType: 'Mixed',
    price: 14602,
    originalPrice: 18990,
    stock: 33,
    images: ['/images/products/baby-boy-harmony-celebration-box.webp'],
    rating: 4.9,
    reviewsCount: 177,
    tag: 'Best Seller',
    description: "A lavish curation of handpicked garden blooms, masterfully arranged in Dhanvikk's signature French velvet keepsake box.",
    isBestSeller: false,
    isFeatured: true,
    inStock: true,
  },
];
